[MQY-1011] Pushing image to registry
cybermerqury/etsi-gs-qkd-014-referenceimplementation pull request #4
Opened 2024-11-14 18:51 UTC by jamesatmerqury

This PR has the changes of https://github.com/cybermerqury/etsi-gs-qkd-014-referenceimplementation/pull/3 and the pipeline.

The pipeline when merged to develop will build, run tests and check the docker file is correct, whilst when merged to main it will do all the mentioned steps and pushing the image in the GitHub registry.

Something important to note is that pushing-image-to-registry branch, was created from improve_docker_image_build branch.

2025-01-07 08:30 UTC, noelatmerqury commented on Dockerfile
> +# # SPDX-FileCopyrightText: © 2023 Merqury Cybersecurity Ltd <info@merqury.eu>
I think these comments were left commented out by mistake?

2025-01-07 09:15 UTC, zachcauchiatmerqury approved these changes
Approved. Minor nitpicks in Dockerfile. great work.

2025-01-07 09:15 UTC, zachcauchiatmerqury commented on Dockerfile
> +
Question: Since the application is being built outside of the Dockerfile and the bundling is being handled below, do we still need this section?

2025-01-07 09:15 UTC, zachcauchiatmerqury commented on Dockerfile
> +# COPY --from=builder /bin/etsi_gs_qkd_014_referenceimplementation ./
Nitpick: I think this can be removed.

2025-01-07 10:08 UTC, zachcauchiatmerqury requested changes
Removing approval until suggestions are addressed.

2025-01-15 16:24 UTC, jamesatmerqury commented on Dockerfile
> +
From line 1 till line 36 is not needed, the pipeline will just push the image needed only

2025-01-15 16:28 UTC, jamesatmerqury commented on Dockerfile
> +# COPY --from=builder /bin/etsi_gs_qkd_014_referenceimplementation ./
Thanks, removed the commented line

2025-01-15 16:30 UTC, jamesatmerqury commented
> Removing approval until suggestions are addressed.

These has been addressed, can you kindly have a look one more time?

2025-01-20 08:00 UTC, zachcauchiatmerqury approved these changes
Approved. No comments from my end. Feel free to merge. Great work! 🚀

2025-02-05 10:43 UTC, merged